### PR TITLE
JavaScript capstone project 

### PR DESCRIPTION
**Pull request by jaflih**
### JavaScript capstone project

- Created homepage with popup
- Added styles (mobile and desktop version)
- Added units tests for a JavaScript app.
- Used callbacks and promises
- Used Webpack.
- Used Follow Gitflow.
- Sent and received data from an API.
- Used API documentation.
- Made JavaScript code synchronous.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @jihaneH,** 

### **To Highlight**

- PR is full of details.
- The video is good.
- The commits are consistent.
- The readme file is good.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._


- Please fix the failing test suits before submitting them for another review.


ppp


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaflih** [comment]
@dasileker  Thank you for the review.
We fix the test.

**Review by Kingstalux — CHANGES_REQUESTED** [review]
Hi @jihaneH and @dasileker , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._
- [ ] Your tests are still not passing. I've included a screenshot below to show the error it says. After fixing the tests, It'll be great if you could include a screenshot of all the tests passing in the review request.

Screenshot 2022-02-03 193346


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by matovu-farid** [comment]
The tests pass. This is a screenshot with evidence
image

**Comment by jaflih** [comment]
Hi @dasileker and @Kingstalux 

Thank's for the review.

Can you help us? because tests are fine on our side.

https://user-images.githubusercontent.com/7243132/152413805-d0e3e66f-024b-4051-9587-048016059961.mp4

**Comment by dasileker** [comment]
Hello I see that you have added a video shows that test are passing, but can someone in your stand up team download the repo and run the test to check.

**Comment by matovu-farid** [comment]
@dasileker, you were right about the first review and we fixed it. But as the second review, the tests passed.

**Comment by jaflih** [comment]
@dasileker, thank's for the feedback.

I record a new video :
clone the project >> npm install >> npm run test

https://user-images.githubusercontent.com/7243132/152418349-bd52dece-7347-4a7d-9bea-e9c39f1bf9ce.mp4

**Review by bimbolabuari — APPROVED** [review]
# Project Approved 🚀

Hi Team🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
